# .github/workflows/create-branch.yml
name: Create Dynamic Branch

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

permissions:
  contents: write  # Required to push branches

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3

      - name: Set dynamic branch name
        id: set_branch
        run: echo "BRANCH=auto-branch-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create and push new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git checkout -b $BRANCH
          git push origin $BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
