# .github/workflows/hourly.yml
name: cron check

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: source env
        run: |
          pwd
          ls 
