# .github/workflows/hourly.yml
name: cron check

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: do stuff
        uses: actions/checkout@v4
        run: |
          LATEST_VERSION="$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" 'https://api.github.com/repos/OasisLMF/OasisLMF/releases/latest' 2> '/dev/null' |  curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" 'https://api.github.com/repos/OasisLMF/OasisLMF/releases/latest' 2> '/dev/null' | grep -E '"name": "Release [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+",' | grep -oE '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]')"

          source .env
          CURRENT_VERSION="$VERSION"

          echo "LATEST_VERSION='$LATEST_VERSION'"
          echo "CURRENT_VERSION='$CURRENT_VERSION'"

          if [[ "$VERSION" != "$LATEST_VERSION" ]]; then
            echo 'not the same version!'
          else
            echo 'the same version'
          fi
